[options]
db_host = localhost
db_port = 5432
db_user = odoo
db_password = a

construction_frontend_url = http://localhost:5173

addons_path = /home/luckas/Documents/Stage/code/odoo17/odoo/addons,/home/luckas/Documents/Stage/code/odoo17/custom-addons/queue,/home/luckas/Documents/Stage/code/odoo17/custom-addons,/home/luckas/.local/share/Odoo/addons/17.0
gevent_port = 8072

workers = 4
server_wide_modules = base,web,queue_job

limit_time_cpu = 3600
limit_time_real = 3600